version: '3'

services:
  user-pg:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tweet
    ports:
      - 5432:5432
    # volumes: postgres
  auth:
    build: auth
    env_file:
      - ./auth/.env
    ports:
      - 8080:8080
    volumes:
      - ./auth:/app:ro
    depends_on:
      - user-pg
# volumes:
#   postgres:
