version: '3'

services:
  user-pg:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tweet
    ports:
      - 5432:5432
  auth:
    build: auth
    env_file:
      - ./auth/.env
    ports:
      - 8080:8080
    volumes:
      - ./auth:/app:ro
    depends_on:
      - user-pg
  user-mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
  user-brain:
    build: user-brain
    env_file:
      - ./user-brain/.env
    ports:
      - 8081:8081
    volumes:
      - ./user-brain:/app:ro
    depends_on:
      - user-mongo
